### ISSUE TITLE
Add activity feed

### ISSUE THREAD

**Issue by agilaz** [aaronjohnweiss/ascndr#66]
On the home page, display a feed of recent activity:
* Climbing session
  * Duration
  * Max grade by style
  * Total routes/total distance?
* Workout
  * Types/intensity
* Video upload
* Milestones
  * New hardest grade
  * X sessions climbed
  * X hours climbed

**Comment by ngattusohw** [comment]
As mentioned in this ticket (https://github.com/aaronjohnweiss/ascndr/issues/72#issuecomment-1605815916) could be cool to see a message that "Ed, Nick and Jenna climbed today" in all of our newsfeeds or something

**Comment by agilaz** [comment]
For future consideration, we could consider setting this up to display more intelligently than just sorting chronologically. We could set up some more important information (e.g. new hardest grade) to be stickier, and display more importantly than less interesting things like a climbing session.

**Comment by ngattusohw** [comment]
future future social considerations? twitter like feed? how do we do this without just making a worse twitter
